### ISSUE TITLE
How to get value selected?

### ISSUE THREAD

**Issue by dangcao410** [DenisHannig/ImageLoader#1]
How to get value selected?

**Comment by DenisHannig** [comment]
Hey there. I'll check this out and reply to you quickly 👍

**Comment by DenisHannig** [comment]
**You could do something like this for example:**
```js
<html>

	<head>
		<script src="image-selector.lib.min.js"></script>
	</head>
  
	<body>
	
		<image-selector id="any_id">
			<image-option id="id1" title="Option 1" image="filename/or/url/" />
			<image-option id="id2" title="Option 2" image="filename/or/url/" />
		</image-selector>
		
		<button onClick="getCurrentSelected();">Get current</button>

	</body>
  
	<script>
		function getCurrentSelected() {
			var selector = document.getElementById('any_id');
			var selectionIndex = ImageSelector.getCurrentSelectedIndex(selector);
			var selection = ImageSelector.getCurrentSelected(selector);
			console.log('selectionIndex', selectionIndex);
			console.log('selection', selection);
		}
	</script>
  
</html>
```

Hope this helps!

I'll update/enhance the README that you can check which functions are available.

*Quick insight:*

`setSelectedIndex(<selector>, <index>)`
`setSelectedOptionById(<selector>, <option_id>)`
`setSelectedOption(<selector>, <option>)`
`setOnSelectListener(<selector>, <callback>)`
`getItemCount(<selector>)`
`getCurrentSelected(<selector>)`
`getCurrentSelectedIndex(<selector>)`
`getIndexOf(<option>)`

**Comment by dangcao410** [comment]
Thanks a lot, a great plugin.

**Comment by DenisHannig** [comment]
Thank you! But still in work! 😇

**Comment by dangcao410** [comment]
I try `setSelectedOptionById(<selector>, <option_id>)` but not working.

```
<image-selector id="select_languages">
        <image-option id="english" title="English" image="images/GB.png" />
        <image-option id="vietnamese" title="Tiếng Việt" image="images/VN.png" />
</image-selector>
```

```
var selector = document.getElementById('select_languages');
ImageSelector.setSelectedOptionById(selector, 'vietnamese');
```

How does it work?

**Comment by DenisHannig** [comment]
Hello! Thanks for asking. Will check this again for you! 😉

**Comment by DenisHannig** [comment]
Where do you put this Javascript part? After `<body></body>` or before? Should be after. But I will improve this to work from any line.

**Comment by dangcao410** [comment]
i have tried before and after `<body></body>` but not working.

**Comment by DenisHannig** [comment]
Is it working for you now? @dangcao410

**Comment by DenisHannig** [comment]
Check out the new Readme 👍 
https://github.com/DenisHannig/ImageDropdownSelector
